DROP TABLE IF EXISTS olist_data;

CREATE TABLE olist_data (
    unnamed_0 TEXT,
    order_id TEXT,
    order_item_id TEXT,
    customer_id TEXT,
    customer_unique_id TEXT,
    customer_zip_code_prefix TEXT,
    customer_city TEXT,
    customer_state TEXT,
    product_id TEXT,
    product_category_name TEXT,
    product_name_lenght TEXT,
    product_description_lenght TEXT,
    product_photos_qty TEXT,
    product_weight_g TEXT,
    product_length_cm TEXT,
    product_height_cm TEXT,
    product_width_cm TEXT,
    seller_id TEXT,
    seller_city TEXT,
    seller_state TEXT,
    seller_zip_code_prefix TEXT,
    payment_type TEXT,
    payment_sequential TEXT,
    payment_installments TEXT,
    price TEXT,
    freight_value TEXT,
    payment_value TEXT,
    shipping_limit_date TEXT,
    order_purchase_timestamp TEXT,
    order_approved_at TEXT,
    order_delivered_carrier_date TEXT,
    order_delivered_customer_date TEXT,
    order_estimated_delivery_date TEXT,
    day_of_purchase TEXT,
    month_of_purchase TEXT,
    year_of_purchase TEXT,
    month_year_of_purchase TEXT,
    order_status TEXT,
    order_unique_id TEXT
);